"""empty message

Revision ID: 529746e1d5df
Revises: 
Create Date: 2021-06-11 10:53:37.168633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529746e1d5df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('postID', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('postID')
    )
    op.create_table('user',
    sa.Column('userNum', sa.Integer(), nullable=False),
    sa.Column('userID', sa.String(length=200), nullable=False),
    sa.Column('userPass', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('userNum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###
